### ISSUE TITLE
Real time readering

### ISSUE THREAD

**Issue by GeorgeS2019** [InfernalWAVE/GD_Spectrogram#2]
Any plan for real time readering?

**Comment by InfernalWAVE** [comment]
> Any plan for real time readering?

shouldn't be too hard. the spectrogram is just the energies array, sampling from the gradient.

i'm already adding to energies every frame. so shouldn't be too hard to just keep a fixed size and and update the image each frame instead of all at once at the end. you could use that image to make an image texture and then use that texture on a texture rect.

**Comment by GeorgeS2019** [comment]
Will this work leads to lipsync

**Comment by InfernalWAVE** [comment]
> Will this work leads to lipsync

that's the plan

**Comment by GeorgeS2019** [comment]
Are U awake of Godot4 facial motion capture using GDMP

It is missing the audio part now for lipsync

**Comment by InfernalWAVE** [comment]
> Are U awake of Godot4 facial motion capture using GDMP
> 
> 
> 
> It is missing the audio part now for lipsync 

could you link it? i actually made my whole own facial and body tracking extension using NVIDIA AR called GD_MAXINE, which is also open source on my account

**Comment by GeorgeS2019** [comment]
https://github.com/j20001970/GDMP-demo/issues/2#issuecomment-1565456337

**Comment by GeorgeS2019** [comment]
Join Godot contribution forum

Currently we are defining gold standards for motion capture 

Please share video of your demo

It is unclear how complicated right now

**Comment by InfernalWAVE** [comment]
will do, i'll record some videos tomorrow. there's really nothing much to see while it runs though, it generates the spectrograms on exit.

you can see more posts on my twitter as well

**Comment by GeorgeS2019** [comment]
I mean the Nividia...I thought I see head mesh?

**Comment by InfernalWAVE** [comment]
> I mean the Nividia...I thought I see head mesh?

ah yes sorry. i thought you meant the spectrogram. i can post some videos to the repo of that now

**Comment by GeorgeS2019** [comment]
I just saw your Twitter 

Could U consider using **Ready Player Me** mesh

**Comment by GeorgeS2019** [comment]
https://youtu.be/puLAC1DB_nQ?si=myi5-LJRIDS__Xbk

**Comment by InfernalWAVE** [comment]
> Any plan for real time readering?

just pushed realtime demo, it uses a different script, but it should all be set up as is. both scripts are in the project folder

**Comment by GeorgeS2019** [comment]
@InfernalWAVE 

![Godot_v4 2 1-stable_mono_win64_vic9k1kAzt](https://github.com/InfernalWAVE/GD_Spectrogram/assets/49812372/0665b329-029a-46c9-8cc4-8b0d17f54640)

**Comment by GeorgeS2019** [comment]
@InfernalWAVE 

One Example of[ Real Time Analysis for LipSync  ](https://github.com/hecomi/uLipSync)
![image](https://github.com/InfernalWAVE/GD_Spectrogram/assets/49812372/7523b92b-e4bc-4257-8005-9263ad072554)
